-- MySQL Script generated by MySQL Workbench
-- 05/19/16 13:13:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OSI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OSI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OSI` DEFAULT CHARACTER SET utf8 ;
USE `OSI` ;

-- -----------------------------------------------------
-- Table `OSI`.`PUNTOS_LIMPIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`PUNTOS_LIMPIOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  `estado` TINYINT NOT NULL,
  `posx` DOUBLE NOT NULL,
  `posy` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI`.`RECICLADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`RECICLADORES` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `posx` DOUBLE NOT NULL,
  `posy` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI`.`JUNTAS_VECINOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`JUNTAS_VECINOS` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `idpunto` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_JUNTAS_VECINOS_1_idx` (`idpunto` ASC),
  CONSTRAINT `fk_JUNTAS_VECINOS_1`
    FOREIGN KEY (`idpunto`)
    REFERENCES `OSI`.`PUNTOS_LIMPIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI`.`EMPRESAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`EMPRESAS` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `posx` DOUBLE NOT NULL,
  `posy` DOUBLE NOT NULL,
  `tipo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI`.`EMPRESAS_PUNTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`EMPRESAS_PUNTOS` (
  `idempresa` INT NOT NULL,
  `idpunto` INT NOT NULL,
  PRIMARY KEY (`idempresa`, `idpunto`),
  INDEX `fk_EMPRESAS_has_PUNTOS_ACOPIO_PUNTOS_ACOPIO1_idx` (`idpunto` ASC),
  INDEX `fk_EMPRESAS_has_PUNTOS_ACOPIO_EMPRESAS1_idx` (`idempresa` ASC),
  CONSTRAINT `fk_EMPRESAS_has_PUNTOS_ACOPIO_EMPRESAS1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `OSI`.`EMPRESAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPRESAS_has_PUNTOS_ACOPIO_PUNTOS_ACOPIO1`
    FOREIGN KEY (`idpunto`)
    REFERENCES `OSI`.`PUNTOS_LIMPIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
