-- MySQL Script generated by MySQL Workbench
-- jue 23 jun 2016 16:22:18 CLT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema OSI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OSI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OSI` DEFAULT CHARACTER SET latin1 ;
USE `OSI` ;

-- -----------------------------------------------------
-- Table `OSI`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`admin` (
  `rut` VARCHAR(25) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenna` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
-- ----------------------------
-- Records of admin
-- ----------------------------
INSERT INTO `admin` VALUES ('19125145-8', 'Anghelo', '123456789', 'alf@alf.alf', '321');
INSERT INTO `admin` VALUES ('9393265-k', 'Eduardo', '67613043', 'correo@correo.com', '123');

-- -----------------------------------------------------
-- Table `OSI`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`empresas` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `posx` DOUBLE NOT NULL,
  `posy` DOUBLE NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `OSI`.`puntos_limpios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`puntos_limpios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(63) NOT NULL,
  `estado` TINYINT(4) NOT NULL,
  `posx` DOUBLE NOT NULL,
  `posy` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;

-- ----------------------------
-- Records of puntos_limpios
-- ----------------------------
INSERT INTO `puntos_limpios` VALUES ('10', 'Tocornal 63, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Botellas', '0', '-33.040180013722534', '-71.60214328905568');
INSERT INTO `puntos_limpios` VALUES ('11', 'Molina 316-380, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Botellas', '0', '-33.04550421736434', '-71.61991024157032');
INSERT INTO `puntos_limpios` VALUES ('12', 'Dante 152, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Botellas', '0', '-33.042622711749644', '-71.63522529881448');
INSERT INTO `puntos_limpios` VALUES ('13', 'Lara 34-36, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Botellas', '0', '-33.02636076699375', '-71.63797188084573');
INSERT INTO `puntos_limpios` VALUES ('14', 'Los Placeres 399, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Botellas', '0', '-33.03669392520552', '-71.59563057124615');
INSERT INTO `puntos_limpios` VALUES ('15', 'Edwards 150, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Botellas', '0', '-33.04464445243333', '-71.61889538168907');
INSERT INTO `puntos_limpios` VALUES ('17', 'Javiera Carrera 426-504, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Botellas', '0', '-33.03795310629821', '-71.59065037965775');
INSERT INTO `puntos_limpios` VALUES ('18', 'Guillermo Munnich 339, ValparaÃ­so, ValparaÃ­so, RegiÃ³n de ValparaÃ­so, Chile', 'Latas', '0', '-33.04687478818968', '-71.63373738527298');
-- -----------------------------------------------------
-- Table `OSI`.`empresas_puntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`empresas_puntos` (
  `empresas_id` INT(11) NOT NULL,
  `puntos_limpios_id` INT(11) NOT NULL,
  PRIMARY KEY (`empresas_id`, `puntos_limpios_id`),
  INDEX `fk_empresas_puntos_empresas1_idx` (`empresas_id` ASC),
  INDEX `fk_empresas_puntos_puntos_limpios1_idx` (`puntos_limpios_id` ASC),
  CONSTRAINT `fk_empresas_puntos_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `OSI`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas_puntos_puntos_limpios1`
    FOREIGN KEY (`puntos_limpios_id`)
    REFERENCES `OSI`.`puntos_limpios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `OSI`.`estados_puntos_limpios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`estados_puntos_limpios` (
  `id_estado` INT(11) NOT NULL,
  `vaciado` TINYINT(4) NOT NULL DEFAULT '0',
  `estado` INT(11) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `puntos_limpios_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_estado`, `puntos_limpios_id`),
  INDEX `fk_estados_puntos_limpios_puntos_limpios1_idx` (`puntos_limpios_id` ASC),
  CONSTRAINT `fk_estados_puntos_limpios_puntos_limpios1`
    FOREIGN KEY (`puntos_limpios_id`)
    REFERENCES `OSI`.`puntos_limpios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- ----------------------------
-- Records of estados_puntos_limpios
-- ----------------------------
INSERT INTO `estados_puntos_limpios` VALUES ('1', '11', '0', '58', '0000-00-00 00:00:00');
INSERT INTO `estados_puntos_limpios` VALUES ('2', '11', '0', '61', '2016-05-23 13:13:10');
INSERT INTO `estados_puntos_limpios` VALUES ('3', '13', '0', '83', '2016-05-24 15:47:57');
INSERT INTO `estados_puntos_limpios` VALUES ('4', '10', '0', '62', '2016-06-01 12:10:12');
INSERT INTO `estados_puntos_limpios` VALUES ('5', '18', '0', '37', '2016-06-09 11:15:04');

-- -----------------------------------------------------
-- Table `OSI`.`juntas_vecinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`juntas_vecinos` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `idpunto` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_JUNTAS_VECINOS_1_idx` (`idpunto` ASC),
  CONSTRAINT `fk_JUNTAS_VECINOS_1`
    FOREIGN KEY (`idpunto`)
    REFERENCES `OSI`.`puntos_limpios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `OSI`.`postulaciones_puntos_limpios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`postulaciones_puntos_limpios` (
  `id_postulacion` INT(11) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `posx` DOUBLE NOT NULL,
  `posy` DOUBLE NOT NULL,
  `revisado` TINYINT(1) NOT NULL,
  `aceptado` TINYINT(1) NOT NULL,
  `juntas_vecinos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_postulacion`, `juntas_vecinos_id`),
  INDEX `fk_postulaciones_puntos_limpios_juntas_vecinos1_idx` (`juntas_vecinos_id` ASC),
  CONSTRAINT `fk_postulaciones_puntos_limpios_juntas_vecinos1`
    FOREIGN KEY (`juntas_vecinos_id`)
    REFERENCES `OSI`.`juntas_vecinos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `OSI`.`recicladores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`recicladores` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `posx` DOUBLE NOT NULL,
  `posy` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `OSI`.`recicladores_puntos_limpios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OSI`.`recicladores_puntos_limpios` (
  `id_estado` INT(11) NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `recicladores_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_estado`, `recicladores_id`),
  INDEX `fk_recicladores_puntos_limpios_recicladores1_idx` (`recicladores_id` ASC),
  CONSTRAINT `fk_recicladores_puntos_limpios_estados_puntos_limpios1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `OSI`.`estados_puntos_limpios` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recicladores_puntos_limpios_recicladores1`
    FOREIGN KEY (`recicladores_id`)
    REFERENCES `OSI`.`recicladores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
